export const questionsData = {
  part1: [
    {
      id: 'q1',
      title: 'Hồ sơ #01: Nhận diện cấu trúc',
      question: 'Phenol là',
      options: [
        { id: 'q1_a', text: 'Hợp chất trong phân tử có một hoặc nhiều nhóm hydroxy liên kết trực tiếp với nguyên tử carbon của vòng benzene.' },
        { id: 'q1_b', text: 'Hợp chất trong phân tử chỉ có một nhóm hydroxy liên kết trực tiếp với nguyên tử carbon của vòng benzene.' },
        { id: 'q1_c', text: 'Hợp chất trong phân tử có một hoặc nhiều nguyên tố halogen liên kết trực tiếp với nguyên tử carbon của vòng benzene.' },
        { id: 'q1_d', text: 'Hợp chất trong phân tử có một hoặc nhiều nhóm hydroxy liên kết trực tiếp với nguyên tử carbon không no.' },
      ],
      correctAnswerId: 'q1_a',
      clue: 'Giới tính: Nữ (Nhiễm sắc thể XX)',
      explanationImage: '/explain_q1.png',
      explanation: '📖 <b>Giải thích:</b> Phenol là hợp chất hữu cơ trong phân tử có <b>một hoặc nhiều nhóm -OH</b> (hydroxy) liên kết <b>trực tiếp</b> với nguyên tử carbon của <b>vòng benzene</b>.<br/><br/>🔑 <b>Phân biệt:</b><br/>• Phenol có thể có <b>nhiều</b> nhóm -OH (ví dụ: catechol có 2 nhóm -OH).<br/>• Dẫn xuất halogen của benzene không phải phenol.<br/>• Alcohol không no khác với phenol vì -OH phải gắn vào <b>vòng benzene</b>.',
    },
    {
      id: 'q2',
      title: 'Hồ sơ #02: Đặc tính vật lý',
      question: 'Tính chất vật lí nào sau đây không phải của phenol?',
      options: [
        { id: 'q2_a', text: 'Không tan trong nước.' },
        { id: 'q2_b', text: 'Chất rắn không màu.' },
        { id: 'q2_c', text: 'Độc và gây bỏng da.' },
        { id: 'q2_d', text: 'Tan tốt trong ethanol.' },
      ],
      correctAnswerId: 'q2_a',
      clue: 'Chiều cao: Nhỉnh hơn mét rưỡi',
      explanationImage: '/explain_q2.png',
      explanation: '📖 <b>Giải thích:</b> Phenol (C₆H₅OH) thực tế <b>ít tan trong nước lạnh</b> nhưng <b>tan vô hạn ở nhiệt độ ≥ 66°C</b>. Nói "không tan trong nước" là <b>không chính xác</b>.<br/><br/>🔑 <b>Tính chất đúng của phenol:</b><br/>• Chất rắn không màu, nóng chảy ở 43°C ✅<br/>• Rất độc, gây bỏng da khi tiếp xúc ✅<br/>• Tan tốt trong ethanol và các dung môi hữu cơ ✅',
    },
    {
      id: 'q3',
      title: 'Hồ sơ #03: Bản chất liên kết',
      question: 'Liên kết O-H của phenol phân cực mạnh hơn so với alcohol là do',
      options: [
        { id: 'q3_a', text: 'ảnh hưởng của vòng benzene.' },
        { id: 'q3_b', text: 'phân tử khối lớn hơn.' },
        { id: 'q3_c', text: 'các nguyên tử carbon có độ âm điện lớn hơn nguyên tử oxygen.' },
        { id: 'q3_d', text: 'đáp án khác.' },
      ],
      correctAnswerId: 'q3_a',
      clue: 'Đặc điểm: Đằng sau thấu kính',
      explanationImage: '/explain_q3.png',
      explanation: '📖 <b>Giải thích:</b> Vòng benzene có hiệu ứng <b>liên hợp p-π</b>, hút cặp electron chưa liên kết của nguyên tử O vào hệ liên hợp.<br/><br/>🔑 <b>Hệ quả:</b><br/>• Mật độ electron trên O <b>giảm</b> → liên kết O-H <b>phân cực mạnh hơn</b> → H linh động hơn.<br/>• Vì vậy phenol có <b>tính acid</b> (yếu), còn alcohol thông thường thì không.',
    },
    {
      id: 'q4',
      title: 'Hồ sơ #04: Định hướng tấn công',
      question: 'Do ảnh hưởng của nhóm -OH, mật độ electron trên vòng benzene của phenol tăng lên nhiều nhất ở các vị trí',
      options: [
        { id: 'q4_a', text: 'ortho' },
        { id: 'q4_b', text: 'ortho và para' },
        { id: 'q4_c', text: 'Chỉ các vị trí meta' },
        { id: 'q4_d', text: 'meta và para' },
      ],
      correctAnswerId: 'q4_b',
      clue: 'Học tập: Tín đồ của Newton',
      explanationImage: '/explain_q4.png',
      explanation: '📖 <b>Giải thích:</b> Nhóm -OH đẩy electron vào vòng benzene qua <b>hiệu ứng liên hợp +C</b>.<br/><br/>🔑 <b>Quy tắc định hướng:</b><br/>• Nhóm -OH là nhóm <b>hoạt hóa vòng</b> và <b>định hướng ortho-para</b>.<br/>• Mật độ electron tăng nhiều nhất ở vị trí <b>ortho</b> (2, 6) và <b>para</b> (4).<br/>• Ví dụ: Phenol + Br₂ → 2,4,6-tribromophenol.',
    },
    {
      id: 'q5',
      title: 'Hồ sơ #05: Ứng dụng thực tiễn',
      question: 'Catechin là một chất chống oxi hóa tự nhiên có nhiều trong lá trà xanh. Công thức cấu tạo khung phân tử của catechin như hình bên dưới.',
      questionSuffix: 'Vậy trong một phân tử Catechin có bao nhiêu nhóm chức phenol?',
      hasImage: true,
      imageUrl: 'https://img.loigiaihay.com/picture/2024/0318/1710729358277-mceclip0.png',
      options: [
        { id: 'q5_a', text: '4' },
        { id: 'q5_b', text: '3' },
        { id: 'q5_c', text: '5' },
        { id: 'q5_d', text: '2' },
      ],
      correctAnswerId: 'q5_a',
      clue: 'Chức vụ: Tay hòm chìa khóa',
      explanation: '📖 <b>Giải thích:</b> Nhóm chức phenol = nhóm -OH gắn <b>trực tiếp vào vòng benzene</b>.<br/><br/>🔑 <b>Cách đếm trong Catechin:</b><br/>• Vòng A: <b>2 nhóm -OH</b> ở vị trí 5 và 7 → <b>2 nhóm phenol</b>.<br/>• Vòng B: <b>2 nhóm -OH</b> ở vị trí 3\' và 4\' → <b>2 nhóm phenol</b>.<br/>• Nhóm -OH ở C3 trên vòng C: gắn vào carbon <b>no</b> → là <b>alcohol</b>.<br/>• Tổng: <b>4 nhóm chức phenol</b>.',
    },
  ],
  part2: [
    {
      id: 'q6',
      title: 'Hồ sơ #06: Phản ứng hóa học',
      question: 'Phenol không tác dụng với chất nào sau đây?',
      options: [
        { id: 'q6_a', text: 'NaOH.' },
        { id: 'q6_b', text: 'Na.' },
        { id: 'q6_c', text: 'NaHCO₃.' },
        { id: 'q6_d', text: 'Br₂.' },
      ],
      correctAnswerId: 'q6_c',
      clue: 'Trang bị: Vân tay bọc polymer',
      explanationImage: '/explain_q6.png',
      explanation: '📖 <b>Giải thích:</b> Phenol có tính acid <b>yếu hơn H₂CO₃</b>, nên <b>không đủ mạnh</b> để phản ứng với NaHCO₃.<br/><br/>🔑 <b>So sánh:</b><br/>• Thứ tự tính acid: HCl >> H₂CO₃ > C₆H₅OH > H₂O<br/>• Phenol + NaOH ✅ | Phenol + Na ✅ | Phenol + Br₂ ✅<br/>• Phenol + NaHCO₃ ❌ KHÔNG phản ứng<br/><br/>💡 Đây là cách phân biệt phenol với acid carboxylic.',
    },
    {
      id: 'q7',
      title: 'Hồ sơ #07: Dấu vết kết tủa',
      question: 'Nhỏ dung dịch Br₂ vào dung dịch phenol sẽ thấy hiện tượng',
      options: [
        { id: 'q7_a', text: 'kết tủa màu vàng.' },
        { id: 'q7_b', text: 'kết tủa màu trắng.' },
        { id: 'q7_c', text: 'sủi bọt khí.' },
        { id: 'q7_d', text: 'kết tủa màu đen.' },
      ],
      correctAnswerId: 'q7_b',
      clue: 'Vị trí hiện tại: Gần ngay trung tâm',
      explanationImage: '/explain_q7.png',
      explanation: '📖 <b>Giải thích:</b> Phenol phản ứng với Br₂ tạo <b>2,4,6-tribromophenol</b> – <b>kết tủa trắng</b>.<br/><br/>🔑 <b>Phương trình:</b> C₆H₅OH + 3Br₂ → C₆H₂Br₃OH↓ + 3HBr<br/><br/>📌 Phản ứng xảy ra ngay điều kiện thường, Br₂ bị mất màu, kết tủa trắng xuất hiện. Đây là phản ứng <b>nhận biết phenol</b>.',
    },
  ],
  passwords: {
    part1to2: 'ACID',
    part2toFinal: 'PICRIC ACID',
  },
};
